[pytest]
addopts = -v -s --headed
log_cli = true
log_level = INFO
markers =
    ness_task: test method for Ness exercise

env =
    BASE_URL=https://practicesoftwaretesting.com
    BROWSER_NAME=firefox

# Default browser choice:
    #   chromium | firefox | webkit | auto
    # Set this to enable Moon (otherwise runs locally):
    # MOON_URL=http://moon.aerokube.local
    # BROWSER_NAME=auto
